#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 27 01:28:08 EDT 2021
# SW Build 3118627 on Tue Feb  9 05:13:49 MST 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sampleIP_tl_behav -key {Behavioral:sim_1:Functional:sampleIP_tl} -tclbatch sampleIP_tl.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -log simulate.log"
xsim sampleIP_tl_behav -key {Behavioral:sim_1:Functional:sampleIP_tl} -tclbatch sampleIP_tl.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -log simulate.log

