# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-4614-vandensp-HP-ZBook-Studio-G4/incrSyn
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.cache/wt [current_project]
set_property parent.project_path /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /tools/CANTimingAnalysis/ch_unit/src/axi_slave.sv
  /tools/CANTimingAnalysis/ch_unit/src/dataSizes.sv
  /tools/CANTimingAnalysis/ch_unit/src/dataTypes.sv
  /tools/CANTimingAnalysis/ch_unit/src/bramController.sv
  /tools/CANTimingAnalysis/ch_unit/src/clkUnit.sv
  /tools/CANTimingAnalysis/ch_unit/src/devDelay_tl.sv
  /tools/CANTimingAnalysis/ch_unit/src/errorDetect.sv
  /tools/CANTimingAnalysis/ch_unit/src/halfDuplexBRAM.sv
  /tools/CANTimingAnalysis/ch_unit/src/idComparator.sv
  /tools/CANTimingAnalysis/ch_unit/src/interframeDetect.sv
  /tools/CANTimingAnalysis/ch_unit/src/legacyIF.sv
  /tools/CANTimingAnalysis/ch_unit/src/legacySync.sv
  /tools/CANTimingAnalysis/ch_unit/src/oneshot.sv
  /tools/CANTimingAnalysis/ch_unit/src/playbackUnit.sv
  /tools/CANTimingAnalysis/ch_unit/src/recordMaster.sv
  /tools/CANTimingAnalysis/ch_unit/src/recordUnit.sv
  /tools/CANTimingAnalysis/ch_unit/src/sampleDetect_tl.sv
  /tools/CANTimingAnalysis/ch_unit/src/signalStorage.sv
  /tools/CANTimingAnalysis/ch_unit/src/sizeDetect.sv
  /tools/CANTimingAnalysis/ch_unit/src/syncUnit.sv
}
read_verilog -library xil_defaultlib {
  /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.srcs/sim_1/imports/src/sampleIP_tl.v
  /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.srcs/constrs_1/imports/constraints/sampleConst.xdc
set_property used_in_implementation false [get_files /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.srcs/constrs_1/imports/constraints/sampleConst.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
