# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/sampleConst.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_cdma_0_0 || ORIG_REF_NAME==design_1_axi_cdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# Block Designs: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sampleIP_tl_0_2/design_1_sampleIP_tl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sampleIP_tl_0_2 || ORIG_REF_NAME==design_1_sampleIP_tl_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_cdma_0_0 || ORIG_REF_NAME==design_1_axi_cdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arsw_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rsw_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awsw_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_wsw_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_bsw_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_s00a2s_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_sarn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_srn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_sawn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_swn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_sbn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_m00s2a_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_m00arn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_m00rn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_m00awn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_m00wn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_m00bn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_m01s2a_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_m01arn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_m01rn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m01awn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m01wn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m01bn_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: /tools/Xilinx/Vivado/2020.2/bin/BCA/BCA.gen/sources_1/bd/design_1/design_1_ooc.xdc
