set_property PACKAGE_PIN Y7 [get_ports dOut_0]
set_property PACKAGE_PIN W8 [get_ports enOut_0]
set_property PACKAGE_PIN W6 [get_ports canIn_0]
set_property SLEW FAST [get_ports dOut_0]
set_property SLEW FAST [get_ports enOut_0]
set_property IOSTANDARD LVTTL [get_ports enOut_0]
set_property IOSTANDARD LVTTL [get_ports dOut_0]
set_property IOSTANDARD LVTTL [get_ports canIn_0]
set_property PACKAGE_PIN V15 [get_ports {metaState_0[0]}]
set_property PACKAGE_PIN W15 [get_ports {metaState_0[1]}]
set_property PACKAGE_PIN T11 [get_ports {metaState_0[2]}]
set_property PACKAGE_PIN T10 [get_ports {metaState_0[3]}]
set_property PACKAGE_PIN W14 [get_ports {metaState_0[4]}]
set_property PACKAGE_PIN Y14 [get_ports {metaState_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {metaState_0[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {metaState_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {metaState_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {metaState_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {metaState_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {metaState_0[0]}]
set_property PACKAGE_PIN T14 [get_ports {ifState_0[0]}]
set_property PACKAGE_PIN T15 [get_ports {ifState_0[1]}]
set_property PACKAGE_PIN P14 [get_ports {ifState_0[2]}]
set_property PACKAGE_PIN R14 [get_ports {ifState_0[3]}]
set_property PACKAGE_PIN U14 [get_ports {ifState_0[4]}]
set_property PACKAGE_PIN U15 [get_ports {ifState_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ifState_0[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ifState_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ifState_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ifState_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ifState_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ifState_0[0]}]

set_input_delay -clock [get_clocks *] -rise 8.000 [list [get_ports -filter { NAME =~  "*" && DIRECTION == "IN" }] [get_ports -filter { NAME =~  "*" && DIRECTION == "IN" }]]

set_false_path -from [get_ports canIn_0] -to [get_pins design_1_i/samplePointDetector_0/inst/axi_slave/sampleDetector/su/timingOut1_reg/D]
set_false_path -from [get_ports canIn_0] -to [get_pins design_1_i/samplePointDetector_0/inst/axi_slave/delayUnit/su/timingOut1_reg/D]
set_false_path -from [get_ports canIn_0] -to [get_pins {design_1_i/samplePointDetector_0/inst/axi_slave/delayUnit/rm/rU/runningTotal_reg[31]/D}]
